
# ci/pipeline.yml
#
# DO NOT MAKE CHANGES TO THIS FILE. Instead, modify ci/pipeline.yml.erb and
# execute build-pipeline-yml.
#
# created: 2019-12-16T16:51:21+09:00
#
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: ubuntu-18.04
  type: docker-image
  source:
    repository: ubuntu
    tag: "18.04"

- name: kubernetes-resource
  type: git
  source:
    uri: git://github.com/robinsegura/kubernetes-resource.git
    branch: master

- name: kubernetes-resource-release
  type: git
  source:
    uri: git://github.com/robinsegura/kubernetes-resource.git
    branch: master
    tag_filter: v*

- name: kubernetes-resource-image-1.21.3
  type: docker-image
  source:
    repository: robinsegura/kubernetes-resource
    tag: "1.21.3"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-latest
  type: docker-image
  source:
    repository: robinsegura/kubernetes-resource
    tag: "latest"
    username: ((docker-username))
    password: ((docker-password))


- name: kubernetes-resource-image-edge
  type: docker-image
  source:
    repository: robinsegura/kubernetes-resource
    tag: edge
    username: ((docker-username))
    password: ((docker-password))


- name: stable-1.21
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.21.txt
    filename: version

- name: latest
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/latest.txt
    filename: version


jobs:
- name: build-kubernetes-resource-image-edge
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: latest
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource/ci/tasks/build-build-args-file.yml
      input_mapping: {version: latest}
    - put: kubernetes-resource-image-edge
      params:
        build: kubernetes-resource
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file

- name: build-kubernetes-resource-image-1.21
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:    
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: stable-1.21
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: stable-1.21}
    - put: kubernetes-resource-image-1.21.3
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file

- name: build-kubernetes-resource-image-latest
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-18.04
        params: {save: true}
        trigger: true
      - get: latest
        trigger: true
    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping: {version: latest}
    - put: kubernetes-resource-image-latest
      params:
        build: kubernetes-resource-release
        load_base: ubuntu-18.04
        build_args_file: output/build-args-file